In [10]:
import numpy as np

In [11]:
"""Check the type of the array and Value type for the given array c"""
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
print(b.dtype)

float64


In [12]:
"""Assign the value 20 for the second element in the given array."""
a = np.array([10, 2, 30, 40,50])
a[1] = 20
print(a)

[10 20 30 40 50]


In [13]:
"""Print the even elements in the given array."""
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[1:9:2])

[2 4 6 8]


In [14]:
"""Find the size ,dimension and shape for the given array b"""
b = np.array([10, 20, 30, 40, 50, 60, 70])
print(b.size)
print(b.shape)

7
(7,)


In [19]:
"""Find the sum of maximum and minimum value in the given numpy array"""
c = np.array([-10, 201, 43, 94, 502])
max_c = c.max()
min_c = c.min()

Suma = max_c + min_c
print(Suma)

492


In [20]:
"""Perform addition operation on the given numpy array arr1 and arr2:"""
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
arrSuma = np.add(arr1, arr2)

print(arrSuma)

[30 32 34 36 38 40]


In [22]:
"""Perform subtraction operation on the given numpy array arr3 and arr4:"""
arr3 = np.array([10, 20, 30, 40, 50, 60])
arr4 = np.array([20, 21, 22, 23, 24, 25])
arrResta = np.subtract(arr3, arr4 )

print(arrResta)


[-10  -1   8  17  26  35]


In [23]:
"""Perform multiply operation on the given numpy array arr5 and arr6:"""
arr5 = np.array([10, 20, 30, 40, 50, 60])
arr6 = np.array([2, 1, 2, 3, 4, 5])
arrMult = np.multiply(arr5, arr6)

print(arrMult)

[ 20  20  60 120 200 300]


In [24]:
"""Perform division operation on the given numpy array arr7 and arr8:"""
arr7 = np.array([10, 20, 30, 40, 50, 60])
arr8 = np.array([3, 5, 10, 8, 2, 33])
arrDiv = np.divide(arr7, arr8)

print(arrDiv)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [25]:
"""Perform dot operation on the given numpy array ar9 and ar10:"""
arr9 = np.array([3, 5])
arr10 = np.array([2, 4])
arrDot = np.dot(arr9, arr10)

print(arrDot)

26


In [26]:
"""Add Constant 5 to the given numpy array arr:"""
arr = np.array([1, 2, 3, -1])
arrAdd = 5 + arr
print(arrAdd)

[6 7 8 4]


In [27]:
"""Make a numpy array within [5, 4] and 6 elements"""
arrLins = np.linspace(5,4, num = 6)
print(arrLins)

[5.  4.8 4.6 4.4 4.2 4. ]


In [28]:
#QUIZ
"""Implement the following vector subtraction in numpy: u-v"""
u = np.array([1, 0])
v = np.array([0, 1])
arrUV = np.subtract(u,v)
print(arrUV)

[ 1 -1]


In [29]:
"""Multiply the numpy array z with -2:"""
z = np.array([2, 4])
z * 2

array([4, 8])

In [31]:
"""Consider the list [1, 2, 3, 4, 5] and [1, 0, 1, 0, 1]. Cast both lists to a numpy array then multiply them together:"""
arrA = np.array([1, 2, 3, 4, 5])
arrB = np.array([1, 0, 1, 0, 1])
arrAB = np.multiply(arrA,arrB)
print(arrAB)

[1 0 3 0 5]
